name: Mirroring
on:
  push:
    branches:
      - main

env:
  MIRROR_URL:
    git@github.com:EpitechPromo2027/B-OOP-400-REN-4-1-arcade-arthur.doriel.git

jobs:
  push_to_mirror:
    needs: check_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
